name: Workflow Test
on:
  push:
    branches:
      - '**'
jobs:
  test1:
    runs-on: self-hosted-arc-runner
    container:
      image: ubuntu
    steps:
      - name: step1
        run: |
          sleep 10
          echo "step1"
  test2:
    runs-on: self-hosted-arc-runner
    container:
      image: ubuntu
    steps:
      - name: step2
        run: |
          sleep 10
          echo "step2"
  test3:
    runs-on: self-hosted-arc-runner
    container:
      image: ubuntu
    steps:
      - name: step3
        run: |
          sleep 10
          echo "step3"
  test4:
    runs-on: self-hosted-arc-runner
    steps:
      - name: step4
        run: |
          sleep 10
          echo "step4"
  test5:
    runs-on: self-hosted-arc-runner
    steps:
      - name: step5
        run: |
          sleep 10
          echo "step5"
  test6:
    runs-on: self-hosted-arc-runner
    steps:
      - name: step6
        run: |
          sleep 10
          echo "step6"
